version: '3.8'
services:
  neo4j:
    image: neo4j:5.5.0
    container_name: neo4j-polymer
    environment:
      - NEO4J_AUTH=neo4j/polymer123
    ports:
      - "7687:7687"
      - "7474:7474"
    volumes:
      - neo4j_data:/data
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: polymer-backend
    env_file:
      - .env
    ports:
      - "5050:5000"
    depends_on:
      - neo4j
    volumes:
      - .:/app
    restart: unless-stopped
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: polymer-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
volumes:
  neo4j_data:
